name: React Continuous Integration

on: [push]

jobs:
  test:
    name: Frontend Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
      working-directory: ./frontend
    - name: yarn install, build, and test
      run: |
        yarn
        yarn build
        yarn test
      working-directory: ./frontend  
